//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace zwg_china.client.framework.ActicityService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportBase", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.ImportBaseOfActivity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetPageListImportBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetPageListImportBaseOfActivity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetRedeemPlansImport))]
    public partial class ImportBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportBaseOfActivity", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport))]
    public partial class ImportBaseOfActivity : zwg_china.client.framework.ActicityService.ImportBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateRedeemRecordsImport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    public partial class CreateRedeemRecordsImport : zwg_china.client.framework.ActicityService.ImportBaseOfActivity {
        
        private int PlanIdField;
        
        private int SumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PlanId {
            get {
                return this.PlanIdField;
            }
            set {
                if ((this.PlanIdField.Equals(value) != true)) {
                    this.PlanIdField = value;
                    this.RaisePropertyChanged("PlanId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPageListImportBase", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetPageListImportBaseOfActivity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetRedeemPlansImport))]
    public partial class GetPageListImportBase : zwg_china.client.framework.ActicityService.ImportBase {
        
        private int PageIndexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPageListImportBaseOfActivity", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.GetRedeemPlansImport))]
    public partial class GetPageListImportBaseOfActivity : zwg_china.client.framework.ActicityService.GetPageListImportBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRedeemRecordsImport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    public partial class GetRedeemRecordsImport : zwg_china.client.framework.ActicityService.GetPageListImportBaseOfActivity {
        
        private System.Nullable<System.DateTime> BeginTimeField;
        
        private System.Nullable<System.DateTime> EndTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((this.BeginTimeField.Equals(value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRedeemPlansImport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    public partial class GetRedeemPlansImport : zwg_china.client.framework.ActicityService.GetPageListImportBaseOfActivity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalResult", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4))]
    public partial class NormalResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageResultOfRedeemRecordExport1C_S7RQu4", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    public partial class PageResultOfRedeemRecordExport1C_S7RQu4 : zwg_china.client.framework.ActicityService.NormalResult {
        
        private int CountOfAllMessageField;
        
        private int CountOfPageField;
        
        private System.Collections.Generic.List<zwg_china.client.framework.ActicityService.RedeemRecordExport> ListField;
        
        private int PageIndeField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountOfAllMessage {
            get {
                return this.CountOfAllMessageField;
            }
            set {
                if ((this.CountOfAllMessageField.Equals(value) != true)) {
                    this.CountOfAllMessageField = value;
                    this.RaisePropertyChanged("CountOfAllMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountOfPage {
            get {
                return this.CountOfPageField;
            }
            set {
                if ((this.CountOfPageField.Equals(value) != true)) {
                    this.CountOfPageField = value;
                    this.RaisePropertyChanged("CountOfPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<zwg_china.client.framework.ActicityService.RedeemRecordExport> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageInde {
            get {
                return this.PageIndeField;
            }
            set {
                if ((this.PageIndeField.Equals(value) != true)) {
                    this.PageIndeField = value;
                    this.RaisePropertyChanged("PageInde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageResultOfRedeemPlanExport1C_S7RQu4", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    public partial class PageResultOfRedeemPlanExport1C_S7RQu4 : zwg_china.client.framework.ActicityService.NormalResult {
        
        private int CountOfAllMessageField;
        
        private int CountOfPageField;
        
        private System.Collections.Generic.List<zwg_china.client.framework.ActicityService.RedeemPlanExport> ListField;
        
        private int PageIndeField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountOfAllMessage {
            get {
                return this.CountOfAllMessageField;
            }
            set {
                if ((this.CountOfAllMessageField.Equals(value) != true)) {
                    this.CountOfAllMessageField = value;
                    this.RaisePropertyChanged("CountOfAllMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountOfPage {
            get {
                return this.CountOfPageField;
            }
            set {
                if ((this.CountOfPageField.Equals(value) != true)) {
                    this.CountOfPageField = value;
                    this.RaisePropertyChanged("CountOfPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<zwg_china.client.framework.ActicityService.RedeemPlanExport> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageInde {
            get {
                return this.PageIndeField;
            }
            set {
                if ((this.PageIndeField.Equals(value) != true)) {
                    this.PageIndeField = value;
                    this.RaisePropertyChanged("PageInde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RedeemPlanExport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    public partial class RedeemPlanExport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime BeginTimeField;
        
        private string CodeField;
        
        private string DescriptionField;
        
        private System.DateTime EndTimeField;
        
        private bool HideField;
        
        private int IdField;
        
        private int IntegralField;
        
        private double MoneyField;
        
        private zwg_china.client.framework.ActicityService.RegularStatus StatusField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((this.BeginTimeField.Equals(value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hide {
            get {
                return this.HideField;
            }
            set {
                if ((this.HideField.Equals(value) != true)) {
                    this.HideField = value;
                    this.RaisePropertyChanged("Hide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Integral {
            get {
                return this.IntegralField;
            }
            set {
                if ((this.IntegralField.Equals(value) != true)) {
                    this.IntegralField = value;
                    this.RaisePropertyChanged("Integral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zwg_china.client.framework.ActicityService.RegularStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RedeemRecordExport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    public partial class RedeemRecordExport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string OwnerField;
        
        private int OwnerIdField;
        
        private zwg_china.client.framework.ActicityService.RedeemSnapshotExport PlanField;
        
        private int PriceOfIntegralField;
        
        private double PriceOfMoneyField;
        
        private int SumField;
        
        private int SumOfIntegralField;
        
        private double SumOfMoneyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OwnerId {
            get {
                return this.OwnerIdField;
            }
            set {
                if ((this.OwnerIdField.Equals(value) != true)) {
                    this.OwnerIdField = value;
                    this.RaisePropertyChanged("OwnerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zwg_china.client.framework.ActicityService.RedeemSnapshotExport Plan {
            get {
                return this.PlanField;
            }
            set {
                if ((object.ReferenceEquals(this.PlanField, value) != true)) {
                    this.PlanField = value;
                    this.RaisePropertyChanged("Plan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PriceOfIntegral {
            get {
                return this.PriceOfIntegralField;
            }
            set {
                if ((this.PriceOfIntegralField.Equals(value) != true)) {
                    this.PriceOfIntegralField = value;
                    this.RaisePropertyChanged("PriceOfIntegral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PriceOfMoney {
            get {
                return this.PriceOfMoneyField;
            }
            set {
                if ((this.PriceOfMoneyField.Equals(value) != true)) {
                    this.PriceOfMoneyField = value;
                    this.RaisePropertyChanged("PriceOfMoney");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SumOfIntegral {
            get {
                return this.SumOfIntegralField;
            }
            set {
                if ((this.SumOfIntegralField.Equals(value) != true)) {
                    this.SumOfIntegralField = value;
                    this.RaisePropertyChanged("SumOfIntegral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double SumOfMoney {
            get {
                return this.SumOfMoneyField;
            }
            set {
                if ((this.SumOfMoneyField.Equals(value) != true)) {
                    this.SumOfMoneyField = value;
                    this.RaisePropertyChanged("SumOfMoney");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RedeemSnapshotExport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.client")]
    public partial class RedeemSnapshotExport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string CodeField;
        
        private string DescriptionField;
        
        private int IdField;
        
        private int IntegralField;
        
        private double MoneyField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Integral {
            get {
                return this.IntegralField;
            }
            set {
                if ((this.IntegralField.Equals(value) != true)) {
                    this.IntegralField = value;
                    this.RaisePropertyChanged("Integral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Money {
            get {
                return this.MoneyField;
            }
            set {
                if ((this.MoneyField.Equals(value) != true)) {
                    this.MoneyField = value;
                    this.RaisePropertyChanged("Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegularStatus", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.model")]
    public enum RegularStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        暂停 = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        未开始 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        正常 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        已过期 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActicityService.IActicityService")]
    public interface IActicityService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IActicityService/GetRedeemPlans", ReplyAction="http://tempuri.org/IActicityService/GetRedeemPlansResponse")]
        System.IAsyncResult BeginGetRedeemPlans(zwg_china.client.framework.ActicityService.GetRedeemPlansImport import, System.AsyncCallback callback, object asyncState);
        
        zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4 EndGetRedeemPlans(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IActicityService/GetRedeemRecords", ReplyAction="http://tempuri.org/IActicityService/GetRedeemRecordsResponse")]
        System.IAsyncResult BeginGetRedeemRecords(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport import, System.AsyncCallback callback, object asyncState);
        
        zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4 EndGetRedeemRecords(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IActicityService/CreateRedeemRecords", ReplyAction="http://tempuri.org/IActicityService/CreateRedeemRecordsResponse")]
        System.IAsyncResult BeginCreateRedeemRecords(zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport import, System.AsyncCallback callback, object asyncState);
        
        zwg_china.client.framework.ActicityService.NormalResult EndCreateRedeemRecords(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IActicityServiceChannel : zwg_china.client.framework.ActicityService.IActicityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRedeemPlansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRedeemPlansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRedeemRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRedeemRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4 Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateRedeemRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateRedeemRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public zwg_china.client.framework.ActicityService.NormalResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((zwg_china.client.framework.ActicityService.NormalResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActicityServiceClient : System.ServiceModel.ClientBase<zwg_china.client.framework.ActicityService.IActicityService>, zwg_china.client.framework.ActicityService.IActicityService {
        
        private BeginOperationDelegate onBeginGetRedeemPlansDelegate;
        
        private EndOperationDelegate onEndGetRedeemPlansDelegate;
        
        private System.Threading.SendOrPostCallback onGetRedeemPlansCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRedeemRecordsDelegate;
        
        private EndOperationDelegate onEndGetRedeemRecordsDelegate;
        
        private System.Threading.SendOrPostCallback onGetRedeemRecordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateRedeemRecordsDelegate;
        
        private EndOperationDelegate onEndCreateRedeemRecordsDelegate;
        
        private System.Threading.SendOrPostCallback onCreateRedeemRecordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ActicityServiceClient() {
        }
        
        public ActicityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActicityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActicityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActicityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetRedeemPlansCompletedEventArgs> GetRedeemPlansCompleted;
        
        public event System.EventHandler<GetRedeemRecordsCompletedEventArgs> GetRedeemRecordsCompleted;
        
        public event System.EventHandler<CreateRedeemRecordsCompletedEventArgs> CreateRedeemRecordsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult zwg_china.client.framework.ActicityService.IActicityService.BeginGetRedeemPlans(zwg_china.client.framework.ActicityService.GetRedeemPlansImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRedeemPlans(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4 zwg_china.client.framework.ActicityService.IActicityService.EndGetRedeemPlans(System.IAsyncResult result) {
            return base.Channel.EndGetRedeemPlans(result);
        }
        
        private System.IAsyncResult OnBeginGetRedeemPlans(object[] inValues, System.AsyncCallback callback, object asyncState) {
            zwg_china.client.framework.ActicityService.GetRedeemPlansImport import = ((zwg_china.client.framework.ActicityService.GetRedeemPlansImport)(inValues[0]));
            return ((zwg_china.client.framework.ActicityService.IActicityService)(this)).BeginGetRedeemPlans(import, callback, asyncState);
        }
        
        private object[] OnEndGetRedeemPlans(System.IAsyncResult result) {
            zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4 retVal = ((zwg_china.client.framework.ActicityService.IActicityService)(this)).EndGetRedeemPlans(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRedeemPlansCompleted(object state) {
            if ((this.GetRedeemPlansCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRedeemPlansCompleted(this, new GetRedeemPlansCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRedeemPlansAsync(zwg_china.client.framework.ActicityService.GetRedeemPlansImport import) {
            this.GetRedeemPlansAsync(import, null);
        }
        
        public void GetRedeemPlansAsync(zwg_china.client.framework.ActicityService.GetRedeemPlansImport import, object userState) {
            if ((this.onBeginGetRedeemPlansDelegate == null)) {
                this.onBeginGetRedeemPlansDelegate = new BeginOperationDelegate(this.OnBeginGetRedeemPlans);
            }
            if ((this.onEndGetRedeemPlansDelegate == null)) {
                this.onEndGetRedeemPlansDelegate = new EndOperationDelegate(this.OnEndGetRedeemPlans);
            }
            if ((this.onGetRedeemPlansCompletedDelegate == null)) {
                this.onGetRedeemPlansCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRedeemPlansCompleted);
            }
            base.InvokeAsync(this.onBeginGetRedeemPlansDelegate, new object[] {
                        import}, this.onEndGetRedeemPlansDelegate, this.onGetRedeemPlansCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult zwg_china.client.framework.ActicityService.IActicityService.BeginGetRedeemRecords(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRedeemRecords(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4 zwg_china.client.framework.ActicityService.IActicityService.EndGetRedeemRecords(System.IAsyncResult result) {
            return base.Channel.EndGetRedeemRecords(result);
        }
        
        private System.IAsyncResult OnBeginGetRedeemRecords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            zwg_china.client.framework.ActicityService.GetRedeemRecordsImport import = ((zwg_china.client.framework.ActicityService.GetRedeemRecordsImport)(inValues[0]));
            return ((zwg_china.client.framework.ActicityService.IActicityService)(this)).BeginGetRedeemRecords(import, callback, asyncState);
        }
        
        private object[] OnEndGetRedeemRecords(System.IAsyncResult result) {
            zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4 retVal = ((zwg_china.client.framework.ActicityService.IActicityService)(this)).EndGetRedeemRecords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRedeemRecordsCompleted(object state) {
            if ((this.GetRedeemRecordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRedeemRecordsCompleted(this, new GetRedeemRecordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRedeemRecordsAsync(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport import) {
            this.GetRedeemRecordsAsync(import, null);
        }
        
        public void GetRedeemRecordsAsync(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport import, object userState) {
            if ((this.onBeginGetRedeemRecordsDelegate == null)) {
                this.onBeginGetRedeemRecordsDelegate = new BeginOperationDelegate(this.OnBeginGetRedeemRecords);
            }
            if ((this.onEndGetRedeemRecordsDelegate == null)) {
                this.onEndGetRedeemRecordsDelegate = new EndOperationDelegate(this.OnEndGetRedeemRecords);
            }
            if ((this.onGetRedeemRecordsCompletedDelegate == null)) {
                this.onGetRedeemRecordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRedeemRecordsCompleted);
            }
            base.InvokeAsync(this.onBeginGetRedeemRecordsDelegate, new object[] {
                        import}, this.onEndGetRedeemRecordsDelegate, this.onGetRedeemRecordsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult zwg_china.client.framework.ActicityService.IActicityService.BeginCreateRedeemRecords(zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateRedeemRecords(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zwg_china.client.framework.ActicityService.NormalResult zwg_china.client.framework.ActicityService.IActicityService.EndCreateRedeemRecords(System.IAsyncResult result) {
            return base.Channel.EndCreateRedeemRecords(result);
        }
        
        private System.IAsyncResult OnBeginCreateRedeemRecords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport import = ((zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport)(inValues[0]));
            return ((zwg_china.client.framework.ActicityService.IActicityService)(this)).BeginCreateRedeemRecords(import, callback, asyncState);
        }
        
        private object[] OnEndCreateRedeemRecords(System.IAsyncResult result) {
            zwg_china.client.framework.ActicityService.NormalResult retVal = ((zwg_china.client.framework.ActicityService.IActicityService)(this)).EndCreateRedeemRecords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateRedeemRecordsCompleted(object state) {
            if ((this.CreateRedeemRecordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateRedeemRecordsCompleted(this, new CreateRedeemRecordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateRedeemRecordsAsync(zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport import) {
            this.CreateRedeemRecordsAsync(import, null);
        }
        
        public void CreateRedeemRecordsAsync(zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport import, object userState) {
            if ((this.onBeginCreateRedeemRecordsDelegate == null)) {
                this.onBeginCreateRedeemRecordsDelegate = new BeginOperationDelegate(this.OnBeginCreateRedeemRecords);
            }
            if ((this.onEndCreateRedeemRecordsDelegate == null)) {
                this.onEndCreateRedeemRecordsDelegate = new EndOperationDelegate(this.OnEndCreateRedeemRecords);
            }
            if ((this.onCreateRedeemRecordsCompletedDelegate == null)) {
                this.onCreateRedeemRecordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateRedeemRecordsCompleted);
            }
            base.InvokeAsync(this.onBeginCreateRedeemRecordsDelegate, new object[] {
                        import}, this.onEndCreateRedeemRecordsDelegate, this.onCreateRedeemRecordsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override zwg_china.client.framework.ActicityService.IActicityService CreateChannel() {
            return new ActicityServiceClientChannel(this);
        }
        
        private class ActicityServiceClientChannel : ChannelBase<zwg_china.client.framework.ActicityService.IActicityService>, zwg_china.client.framework.ActicityService.IActicityService {
            
            public ActicityServiceClientChannel(System.ServiceModel.ClientBase<zwg_china.client.framework.ActicityService.IActicityService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetRedeemPlans(zwg_china.client.framework.ActicityService.GetRedeemPlansImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("GetRedeemPlans", _args, callback, asyncState);
                return _result;
            }
            
            public zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4 EndGetRedeemPlans(System.IAsyncResult result) {
                object[] _args = new object[0];
                zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4 _result = ((zwg_china.client.framework.ActicityService.PageResultOfRedeemPlanExport1C_S7RQu4)(base.EndInvoke("GetRedeemPlans", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRedeemRecords(zwg_china.client.framework.ActicityService.GetRedeemRecordsImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("GetRedeemRecords", _args, callback, asyncState);
                return _result;
            }
            
            public zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4 EndGetRedeemRecords(System.IAsyncResult result) {
                object[] _args = new object[0];
                zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4 _result = ((zwg_china.client.framework.ActicityService.PageResultOfRedeemRecordExport1C_S7RQu4)(base.EndInvoke("GetRedeemRecords", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateRedeemRecords(zwg_china.client.framework.ActicityService.CreateRedeemRecordsImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("CreateRedeemRecords", _args, callback, asyncState);
                return _result;
            }
            
            public zwg_china.client.framework.ActicityService.NormalResult EndCreateRedeemRecords(System.IAsyncResult result) {
                object[] _args = new object[0];
                zwg_china.client.framework.ActicityService.NormalResult _result = ((zwg_china.client.framework.ActicityService.NormalResult)(base.EndInvoke("CreateRedeemRecords", _args, result)));
                return _result;
            }
        }
    }
}
