//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace zwg_china.backstage.framework.MessageService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportBase", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.ImportBaseOfMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.CreateBulleinImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.EditBulleinImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.RemoveBulleinImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.GetPageListImportBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.GetPageListImportBaseOfMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.GetBulletinsImport))]
    public partial class ImportBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ImportBaseOfMessage", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.backstage")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.CreateBulleinImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.EditBulleinImport))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.RemoveBulleinImport))]
    public partial class ImportBaseOfMessage : zwg_china.backstage.framework.MessageService.ImportBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBulleinImport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.backstage")]
    public partial class CreateBulleinImport : zwg_china.backstage.framework.MessageService.ImportBaseOfMessage {
        
        private System.DateTime BeginTimeField;
        
        private string ContextField;
        
        private System.DateTime EndTimeField;
        
        private bool HideField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((this.BeginTimeField.Equals(value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hide {
            get {
                return this.HideField;
            }
            set {
                if ((this.HideField.Equals(value) != true)) {
                    this.HideField = value;
                    this.RaisePropertyChanged("Hide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditBulleinImport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.backstage")]
    public partial class EditBulleinImport : zwg_china.backstage.framework.MessageService.ImportBaseOfMessage {
        
        private System.DateTime BeginTimeField;
        
        private string ContextField;
        
        private System.DateTime EndTimeField;
        
        private bool HideField;
        
        private int IdField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((this.BeginTimeField.Equals(value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hide {
            get {
                return this.HideField;
            }
            set {
                if ((this.HideField.Equals(value) != true)) {
                    this.HideField = value;
                    this.RaisePropertyChanged("Hide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveBulleinImport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.backstage")]
    public partial class RemoveBulleinImport : zwg_china.backstage.framework.MessageService.ImportBaseOfMessage {
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPageListImportBase", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.GetPageListImportBaseOfMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.GetBulletinsImport))]
    public partial class GetPageListImportBase : zwg_china.backstage.framework.MessageService.ImportBase {
        
        private int PageIndexField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPageListImportBaseOfMessage", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.backstage")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.GetBulletinsImport))]
    public partial class GetPageListImportBaseOfMessage : zwg_china.backstage.framework.MessageService.GetPageListImportBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBulletinsImport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.backstage")]
    public partial class GetBulletinsImport : zwg_china.backstage.framework.MessageService.GetPageListImportBaseOfMessage {
        
        private string KeywordOfTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KeywordOfTitle {
            get {
                return this.KeywordOfTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordOfTitleField, value) != true)) {
                    this.KeywordOfTitleField = value;
                    this.RaisePropertyChanged("KeywordOfTitle");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NormalResult", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx))]
    public partial class NormalResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ErrorField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageResultOfBulletinExportnxyTI_PDx", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service")]
    public partial class PageResultOfBulletinExportnxyTI_PDx : zwg_china.backstage.framework.MessageService.NormalResult {
        
        private int CountOfAllMessageField;
        
        private int CountOfPageField;
        
        private System.Collections.Generic.List<zwg_china.backstage.framework.MessageService.BulletinExport> ListField;
        
        private int PageIndeField;
        
        private int PageSizeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountOfAllMessage {
            get {
                return this.CountOfAllMessageField;
            }
            set {
                if ((this.CountOfAllMessageField.Equals(value) != true)) {
                    this.CountOfAllMessageField = value;
                    this.RaisePropertyChanged("CountOfAllMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CountOfPage {
            get {
                return this.CountOfPageField;
            }
            set {
                if ((this.CountOfPageField.Equals(value) != true)) {
                    this.CountOfPageField = value;
                    this.RaisePropertyChanged("CountOfPage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<zwg_china.backstage.framework.MessageService.BulletinExport> List {
            get {
                return this.ListField;
            }
            set {
                if ((object.ReferenceEquals(this.ListField, value) != true)) {
                    this.ListField = value;
                    this.RaisePropertyChanged("List");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageInde {
            get {
                return this.PageIndeField;
            }
            set {
                if ((this.PageIndeField.Equals(value) != true)) {
                    this.PageIndeField = value;
                    this.RaisePropertyChanged("PageInde");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulletinExport", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.service.backstage")]
    public partial class BulletinExport : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime BeginTimeField;
        
        private string ContextField;
        
        private System.DateTime EndTimeField;
        
        private bool HideField;
        
        private int IdField;
        
        private zwg_china.backstage.framework.MessageService.RegularStatus StatusField;
        
        private string TitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BeginTime {
            get {
                return this.BeginTimeField;
            }
            set {
                if ((this.BeginTimeField.Equals(value) != true)) {
                    this.BeginTimeField = value;
                    this.RaisePropertyChanged("BeginTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Context {
            get {
                return this.ContextField;
            }
            set {
                if ((object.ReferenceEquals(this.ContextField, value) != true)) {
                    this.ContextField = value;
                    this.RaisePropertyChanged("Context");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndTime {
            get {
                return this.EndTimeField;
            }
            set {
                if ((this.EndTimeField.Equals(value) != true)) {
                    this.EndTimeField = value;
                    this.RaisePropertyChanged("EndTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Hide {
            get {
                return this.HideField;
            }
            set {
                if ((this.HideField.Equals(value) != true)) {
                    this.HideField = value;
                    this.RaisePropertyChanged("Hide");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public zwg_china.backstage.framework.MessageService.RegularStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegularStatus", Namespace="http://schemas.datacontract.org/2004/07/zwg_china.model")]
    public enum RegularStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        暂停 = -1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        未开始 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        正常 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        已过期 = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageService.IMessageService")]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/GetBulletins", ReplyAction="http://tempuri.org/IMessageService/GetBulletinsResponse")]
        System.IAsyncResult BeginGetBulletins(zwg_china.backstage.framework.MessageService.GetBulletinsImport import, System.AsyncCallback callback, object asyncState);
        
        zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx EndGetBulletins(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/CreateBullein", ReplyAction="http://tempuri.org/IMessageService/CreateBulleinResponse")]
        System.IAsyncResult BeginCreateBullein(zwg_china.backstage.framework.MessageService.CreateBulleinImport import, System.AsyncCallback callback, object asyncState);
        
        zwg_china.backstage.framework.MessageService.NormalResult EndCreateBullein(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/EditBullein", ReplyAction="http://tempuri.org/IMessageService/EditBulleinResponse")]
        System.IAsyncResult BeginEditBullein(zwg_china.backstage.framework.MessageService.EditBulleinImport import, System.AsyncCallback callback, object asyncState);
        
        zwg_china.backstage.framework.MessageService.NormalResult EndEditBullein(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMessageService/RemoveBullein", ReplyAction="http://tempuri.org/IMessageService/RemoveBulleinResponse")]
        System.IAsyncResult BeginRemoveBullein(zwg_china.backstage.framework.MessageService.RemoveBulleinImport import, System.AsyncCallback callback, object asyncState);
        
        zwg_china.backstage.framework.MessageService.NormalResult EndRemoveBullein(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : zwg_china.backstage.framework.MessageService.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetBulletinsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetBulletinsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateBulleinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateBulleinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public zwg_china.backstage.framework.MessageService.NormalResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((zwg_china.backstage.framework.MessageService.NormalResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EditBulleinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public EditBulleinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public zwg_china.backstage.framework.MessageService.NormalResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((zwg_china.backstage.framework.MessageService.NormalResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoveBulleinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RemoveBulleinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public zwg_china.backstage.framework.MessageService.NormalResult Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((zwg_china.backstage.framework.MessageService.NormalResult)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<zwg_china.backstage.framework.MessageService.IMessageService>, zwg_china.backstage.framework.MessageService.IMessageService {
        
        private BeginOperationDelegate onBeginGetBulletinsDelegate;
        
        private EndOperationDelegate onEndGetBulletinsDelegate;
        
        private System.Threading.SendOrPostCallback onGetBulletinsCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateBulleinDelegate;
        
        private EndOperationDelegate onEndCreateBulleinDelegate;
        
        private System.Threading.SendOrPostCallback onCreateBulleinCompletedDelegate;
        
        private BeginOperationDelegate onBeginEditBulleinDelegate;
        
        private EndOperationDelegate onEndEditBulleinDelegate;
        
        private System.Threading.SendOrPostCallback onEditBulleinCompletedDelegate;
        
        private BeginOperationDelegate onBeginRemoveBulleinDelegate;
        
        private EndOperationDelegate onEndRemoveBulleinDelegate;
        
        private System.Threading.SendOrPostCallback onRemoveBulleinCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("无法设置 CookieContainer。请确保绑定包含 HttpCookieContainerBindingElement。");
                }
            }
        }
        
        public event System.EventHandler<GetBulletinsCompletedEventArgs> GetBulletinsCompleted;
        
        public event System.EventHandler<CreateBulleinCompletedEventArgs> CreateBulleinCompleted;
        
        public event System.EventHandler<EditBulleinCompletedEventArgs> EditBulleinCompleted;
        
        public event System.EventHandler<RemoveBulleinCompletedEventArgs> RemoveBulleinCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult zwg_china.backstage.framework.MessageService.IMessageService.BeginGetBulletins(zwg_china.backstage.framework.MessageService.GetBulletinsImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetBulletins(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx zwg_china.backstage.framework.MessageService.IMessageService.EndGetBulletins(System.IAsyncResult result) {
            return base.Channel.EndGetBulletins(result);
        }
        
        private System.IAsyncResult OnBeginGetBulletins(object[] inValues, System.AsyncCallback callback, object asyncState) {
            zwg_china.backstage.framework.MessageService.GetBulletinsImport import = ((zwg_china.backstage.framework.MessageService.GetBulletinsImport)(inValues[0]));
            return ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).BeginGetBulletins(import, callback, asyncState);
        }
        
        private object[] OnEndGetBulletins(System.IAsyncResult result) {
            zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx retVal = ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).EndGetBulletins(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetBulletinsCompleted(object state) {
            if ((this.GetBulletinsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetBulletinsCompleted(this, new GetBulletinsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetBulletinsAsync(zwg_china.backstage.framework.MessageService.GetBulletinsImport import) {
            this.GetBulletinsAsync(import, null);
        }
        
        public void GetBulletinsAsync(zwg_china.backstage.framework.MessageService.GetBulletinsImport import, object userState) {
            if ((this.onBeginGetBulletinsDelegate == null)) {
                this.onBeginGetBulletinsDelegate = new BeginOperationDelegate(this.OnBeginGetBulletins);
            }
            if ((this.onEndGetBulletinsDelegate == null)) {
                this.onEndGetBulletinsDelegate = new EndOperationDelegate(this.OnEndGetBulletins);
            }
            if ((this.onGetBulletinsCompletedDelegate == null)) {
                this.onGetBulletinsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetBulletinsCompleted);
            }
            base.InvokeAsync(this.onBeginGetBulletinsDelegate, new object[] {
                        import}, this.onEndGetBulletinsDelegate, this.onGetBulletinsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult zwg_china.backstage.framework.MessageService.IMessageService.BeginCreateBullein(zwg_china.backstage.framework.MessageService.CreateBulleinImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateBullein(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zwg_china.backstage.framework.MessageService.NormalResult zwg_china.backstage.framework.MessageService.IMessageService.EndCreateBullein(System.IAsyncResult result) {
            return base.Channel.EndCreateBullein(result);
        }
        
        private System.IAsyncResult OnBeginCreateBullein(object[] inValues, System.AsyncCallback callback, object asyncState) {
            zwg_china.backstage.framework.MessageService.CreateBulleinImport import = ((zwg_china.backstage.framework.MessageService.CreateBulleinImport)(inValues[0]));
            return ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).BeginCreateBullein(import, callback, asyncState);
        }
        
        private object[] OnEndCreateBullein(System.IAsyncResult result) {
            zwg_china.backstage.framework.MessageService.NormalResult retVal = ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).EndCreateBullein(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateBulleinCompleted(object state) {
            if ((this.CreateBulleinCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateBulleinCompleted(this, new CreateBulleinCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateBulleinAsync(zwg_china.backstage.framework.MessageService.CreateBulleinImport import) {
            this.CreateBulleinAsync(import, null);
        }
        
        public void CreateBulleinAsync(zwg_china.backstage.framework.MessageService.CreateBulleinImport import, object userState) {
            if ((this.onBeginCreateBulleinDelegate == null)) {
                this.onBeginCreateBulleinDelegate = new BeginOperationDelegate(this.OnBeginCreateBullein);
            }
            if ((this.onEndCreateBulleinDelegate == null)) {
                this.onEndCreateBulleinDelegate = new EndOperationDelegate(this.OnEndCreateBullein);
            }
            if ((this.onCreateBulleinCompletedDelegate == null)) {
                this.onCreateBulleinCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateBulleinCompleted);
            }
            base.InvokeAsync(this.onBeginCreateBulleinDelegate, new object[] {
                        import}, this.onEndCreateBulleinDelegate, this.onCreateBulleinCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult zwg_china.backstage.framework.MessageService.IMessageService.BeginEditBullein(zwg_china.backstage.framework.MessageService.EditBulleinImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginEditBullein(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zwg_china.backstage.framework.MessageService.NormalResult zwg_china.backstage.framework.MessageService.IMessageService.EndEditBullein(System.IAsyncResult result) {
            return base.Channel.EndEditBullein(result);
        }
        
        private System.IAsyncResult OnBeginEditBullein(object[] inValues, System.AsyncCallback callback, object asyncState) {
            zwg_china.backstage.framework.MessageService.EditBulleinImport import = ((zwg_china.backstage.framework.MessageService.EditBulleinImport)(inValues[0]));
            return ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).BeginEditBullein(import, callback, asyncState);
        }
        
        private object[] OnEndEditBullein(System.IAsyncResult result) {
            zwg_china.backstage.framework.MessageService.NormalResult retVal = ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).EndEditBullein(result);
            return new object[] {
                    retVal};
        }
        
        private void OnEditBulleinCompleted(object state) {
            if ((this.EditBulleinCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.EditBulleinCompleted(this, new EditBulleinCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void EditBulleinAsync(zwg_china.backstage.framework.MessageService.EditBulleinImport import) {
            this.EditBulleinAsync(import, null);
        }
        
        public void EditBulleinAsync(zwg_china.backstage.framework.MessageService.EditBulleinImport import, object userState) {
            if ((this.onBeginEditBulleinDelegate == null)) {
                this.onBeginEditBulleinDelegate = new BeginOperationDelegate(this.OnBeginEditBullein);
            }
            if ((this.onEndEditBulleinDelegate == null)) {
                this.onEndEditBulleinDelegate = new EndOperationDelegate(this.OnEndEditBullein);
            }
            if ((this.onEditBulleinCompletedDelegate == null)) {
                this.onEditBulleinCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnEditBulleinCompleted);
            }
            base.InvokeAsync(this.onBeginEditBulleinDelegate, new object[] {
                        import}, this.onEndEditBulleinDelegate, this.onEditBulleinCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult zwg_china.backstage.framework.MessageService.IMessageService.BeginRemoveBullein(zwg_china.backstage.framework.MessageService.RemoveBulleinImport import, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRemoveBullein(import, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        zwg_china.backstage.framework.MessageService.NormalResult zwg_china.backstage.framework.MessageService.IMessageService.EndRemoveBullein(System.IAsyncResult result) {
            return base.Channel.EndRemoveBullein(result);
        }
        
        private System.IAsyncResult OnBeginRemoveBullein(object[] inValues, System.AsyncCallback callback, object asyncState) {
            zwg_china.backstage.framework.MessageService.RemoveBulleinImport import = ((zwg_china.backstage.framework.MessageService.RemoveBulleinImport)(inValues[0]));
            return ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).BeginRemoveBullein(import, callback, asyncState);
        }
        
        private object[] OnEndRemoveBullein(System.IAsyncResult result) {
            zwg_china.backstage.framework.MessageService.NormalResult retVal = ((zwg_china.backstage.framework.MessageService.IMessageService)(this)).EndRemoveBullein(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRemoveBulleinCompleted(object state) {
            if ((this.RemoveBulleinCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RemoveBulleinCompleted(this, new RemoveBulleinCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RemoveBulleinAsync(zwg_china.backstage.framework.MessageService.RemoveBulleinImport import) {
            this.RemoveBulleinAsync(import, null);
        }
        
        public void RemoveBulleinAsync(zwg_china.backstage.framework.MessageService.RemoveBulleinImport import, object userState) {
            if ((this.onBeginRemoveBulleinDelegate == null)) {
                this.onBeginRemoveBulleinDelegate = new BeginOperationDelegate(this.OnBeginRemoveBullein);
            }
            if ((this.onEndRemoveBulleinDelegate == null)) {
                this.onEndRemoveBulleinDelegate = new EndOperationDelegate(this.OnEndRemoveBullein);
            }
            if ((this.onRemoveBulleinCompletedDelegate == null)) {
                this.onRemoveBulleinCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRemoveBulleinCompleted);
            }
            base.InvokeAsync(this.onBeginRemoveBulleinDelegate, new object[] {
                        import}, this.onEndRemoveBulleinDelegate, this.onRemoveBulleinCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override zwg_china.backstage.framework.MessageService.IMessageService CreateChannel() {
            return new MessageServiceClientChannel(this);
        }
        
        private class MessageServiceClientChannel : ChannelBase<zwg_china.backstage.framework.MessageService.IMessageService>, zwg_china.backstage.framework.MessageService.IMessageService {
            
            public MessageServiceClientChannel(System.ServiceModel.ClientBase<zwg_china.backstage.framework.MessageService.IMessageService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetBulletins(zwg_china.backstage.framework.MessageService.GetBulletinsImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("GetBulletins", _args, callback, asyncState);
                return _result;
            }
            
            public zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx EndGetBulletins(System.IAsyncResult result) {
                object[] _args = new object[0];
                zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx _result = ((zwg_china.backstage.framework.MessageService.PageResultOfBulletinExportnxyTI_PDx)(base.EndInvoke("GetBulletins", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateBullein(zwg_china.backstage.framework.MessageService.CreateBulleinImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("CreateBullein", _args, callback, asyncState);
                return _result;
            }
            
            public zwg_china.backstage.framework.MessageService.NormalResult EndCreateBullein(System.IAsyncResult result) {
                object[] _args = new object[0];
                zwg_china.backstage.framework.MessageService.NormalResult _result = ((zwg_china.backstage.framework.MessageService.NormalResult)(base.EndInvoke("CreateBullein", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginEditBullein(zwg_china.backstage.framework.MessageService.EditBulleinImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("EditBullein", _args, callback, asyncState);
                return _result;
            }
            
            public zwg_china.backstage.framework.MessageService.NormalResult EndEditBullein(System.IAsyncResult result) {
                object[] _args = new object[0];
                zwg_china.backstage.framework.MessageService.NormalResult _result = ((zwg_china.backstage.framework.MessageService.NormalResult)(base.EndInvoke("EditBullein", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginRemoveBullein(zwg_china.backstage.framework.MessageService.RemoveBulleinImport import, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = import;
                System.IAsyncResult _result = base.BeginInvoke("RemoveBullein", _args, callback, asyncState);
                return _result;
            }
            
            public zwg_china.backstage.framework.MessageService.NormalResult EndRemoveBullein(System.IAsyncResult result) {
                object[] _args = new object[0];
                zwg_china.backstage.framework.MessageService.NormalResult _result = ((zwg_china.backstage.framework.MessageService.NormalResult)(base.EndInvoke("RemoveBullein", _args, result)));
                return _result;
            }
        }
    }
}
